import './globals.css';
import '@radix-ui/themes/styles.css';
import { Inter } from 'next/font/google';
import { Theme } from '@radix-ui/themes';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className}`}>
				<Theme
					accentColor="jade"
					grayColor="slate"
					panelBackground="solid"
					radius="medium"
					appearance="dark"
				>
					{children}
				</Theme>
			</body>
		</html>
	);
}
